### ISSUE TITLE
Investigate if LB could reuse for different services

### ISSUE THREAD

**Issue by calvinyv** [yunify/qingcloud-cloud-controller-manager#22]
2，每个service都会新建一个负载均衡器，多个server是否可以复用同一个负载均衡，每个负载均衡可以有10个监听器，理论上10个service可以关联至同一个负载均衡器上，只关联一个太浪费，所以是否能在service的annotations配置项里制定复用已存在的负载均衡器

**Comment by magicsong** [comment]
i will try

**Comment by magicsong** [comment]
done in #46
