### ISSUE TITLE
LoadBalancer 改进

### ISSUE THREAD

**Issue by jolestar** [yunify/qingcloud-cloud-controller-manager#3]
- [ ] 用户不需要设置任何 annotation 就可以创建 LoadBalancer，默认创建私网的 LoadBalancer(或者公网？主要考虑到国内公网 ip 的成本比较高).
- [ ]  私网的 LoadBalancer 不需要用户指定 vxnet，默认使用当前集群所在的 vxnet，通过 cloud config 指定默认的 vxnet。

**Comment by calvinyv** [comment]
需要考虑用户设定了部分annotation的情况么？比如balancemode，或者lbtype

**Comment by jolestar** [comment]
需要考虑。
